# Copyright 2015–2020 Kullo GmbH
#
# This source code is licensed under the 3-clause BSD license. See LICENSE.txt
# in the root directory of this source tree for details.
# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(editable=False)),
                ('keysafe', models.TextField(editable=False)),
                ('attachments', models.BinaryField()),
            ],
            options={
                'managed': False,
                'db_table': 'messages',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(editable=False, max_length=50, unique=True)),
                ('storage_quota', models.IntegerField(editable=False)),
            ],
            options={
                'ordering': ('storage_quota',),
                'managed': False,
                'db_table': 'plans',
            },
        ),
    ]
